#ifndef VARIABLE_DEFINES_H
#define VARIABLE_DEFINES_H

#define ENTITY_MOVE_SPEED 180.0f
#define TILE_SIZE 38.0f
#define KEY_HUD_SIZE 15.0f
#define KEY_HUD_OFFSET 15.0f

#define DEATH_ANIM_SPEED_X 80.f
#define DEATH_ANIM_START_OFFSET_X -25.0f
#define DEATH_ANIM_OFFSET_Y ((((DEATH_ANIM_START_OFFSET_X * DEATH_ANIM_START_OFFSET_X) - (2 * DEATH_ANIM_START_OFFSET_X) - 3) * 0.1))
#define DEATH_ANIM_CUTOFF_Y 300.0f

#endif